### ISSUE TITLE
Ghosts'n Demons Support?

### ISSUE THREAD

**Issue by owlnonymous** [SumolX/MiSTer_OpenBOR#1]
Any chance of Ghosts'n Demons support? I believe it is based on a later version of OpenBOR and has been heavily modified. You can download a free version and get the .pak from https://bonusjz.itch.io/ghostsn-demons

**Comment by SumolX** [comment]
If you can get the version number of the engine I can look into updating the core and it maybe possible.

**Comment by SumolX** [comment]
I looked into this mod and while it's almost compatible the author modified the game engine and did not release the source changes which he is allowed to do since the license is BSD based.  I'm going to close out this issue since there is not much else that can be done without the original sources.

**Comment by owlnonymous** [comment]
I appreciate you giving it a look.
